### ISSUE TITLE
Please enable HTTPS

### ISSUE THREAD

**Issue by ryukinix** [lubien/lubien.github.io#1]
As:

![image](https://user-images.githubusercontent.com/7642878/37026250-b306d64e-2125-11e8-88ed-48d9f731541d.png)

Ps.: This is a new github feature for custom domains with SSL certs because Google is bashing people in the score of search engine. Be watch.

**Comment by ryukinix** [comment]
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by lubien** [comment]
Done. F u. Thanks.
